org.gradle.jvmargs=-Xmx1G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

# Shared Properties
minecraft_version=1.21.1
minecraft_version_range=[1.21.1,1.22)
mod_id=betterdiscs
mod_license=All Rights Reserved
mod_group_id=net.ultimporks.betterdiscs
mod_authors=UltimatePorkerz
mod_description=Useful blocks for Records, and Jukebox/Noteblock

# NeoForge Properties
neo_version=21.1.172
neo_version_range=[21.1.0,)
neo_loader_version_range=[4,)
neo_mod_name=betterdiscs-v1.2.0+1.21.1+NEOFORGE
# MOD VERSION
neo_mod_version=v1.2.0+1.21.1+NEOFORGE

# Neo Parchment
neo_parchment_minecraft_version=1.21.1
neo_parchment_mappings_version=2024.11.13

# NeoForge Jei
neo_jei_version=19.21.0.247