
modLoader="javafml"
loaderVersion="${loader_version_range}"
license="mit"
[[mods]]
modId="betterdiscs"
version="1.0.0"
displayName="Jukebox Speaker"
authors="UltimatePorkerz"
description='''${mod_description}'''

[[dependencies.betterdiscs]]
    modId="forge"
    mandatory=true
    versionRange="${forge_version_range}"
    ordering="NONE"
    side="BOTH"
[[dependencies.betterdiscs]]
    modId="minecraft"
    mandatory=true
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"

[[mixins]]
config="mixins.betterdiscs.json"