
modLoader="javafml"
loaderVersion="[52,)"
license="mit"

[[mods]]
modId= "betterdiscs"
version= "1.0.1beta"
displayName= "Jukebox Speaker"
authors= "UltimatePorkerz"
description= '''Useful blocks for Records, and Jukebox/Noteblock'''

[[dependencies.betterdiscs]]
    modId="forge"
    mandatory=true
    versionRange="[52,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.betterdiscs]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.21.1,1.21.2)"
    ordering="NONE"
    side="BOTH"

[[mixins]]
config="mixins.betterdiscs.json"